import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    // backgroundColor: 'green',
  },
  backgourndHeader: {
    width: '100%',
    height: 200,
    // borderWidth: 1,
  },
  header: {
    height: 80,
    width: '100%',
    marginTop: 10,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingHorizontal: '5%',
  },
  welcome: {
    // right: 10,
    // borderWidth: 1,
    marginTop: '2%',
  },
  pactIcon: {
    marginTop: '1%',
    // borderWidth: 1,
    height: '60%',
  },
  iconImage: {
    height: 40,
    width: 40,
    justifyContent: 'center',
    borderRadius: 50,
    // marginRight: 10,
    // maxWidth: 25,
  },
  tagName: {
    // borderWidth: 1,
    // maxWidth: '100%',
  },
  icon: {
    // borderWidth: 1,
    borderRadius: 50,
    // marginRight: '2%',
    // marginTop: '3%',
    borderColor: '#a9a9a9',
  },
  body: {
    // borderTopEndRadius: 10,
    // borderTopStartRadius: 10,
    width: '100%',
    height: 180,
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
    elevation: 5,
    bottom: 5,
    borderRadius: 10,
    // borderWidth: 1,
  },
  order: {
    borderRadius: 10,
    marginTop: '2%',
    marginBottom: '2%',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '20%',
    elevation: 5,
  },
  order1: {
    borderRadius: 10,
    marginTop: '2%',
    marginBottom: '2%',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 30,
    elevation: 5,
  },
  color: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    flexDirection: 'row',
  },
  color1: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    flexDirection: 'row',
  },
  text: {
    fontSize: 17,
    color: '#FFFF',
  },
  patchTitle: {
    flexDirection: 'row',
    borderWidth: 1,
    justifyContent: 'space-between',
    marginTop: 5,
  },
  buttom: {
    // borderWidth: 1,
    backgroundColor: '#FFFF',
    width: '100%',
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    paddingHorizontal: 10,
  },
  data: {
    backgroundColor: '#ffff',
    elevation: 5,
    width: 150,
    height: '80%',
    marginLeft: 10,
    borderRadius: 10,
    marginTop: 5,
    paddingHorizontal: 10,
    alignItems: 'center',
    paddingVertical: 5,
    flexDirection: 'row',
    // borderWidth: 1,
  },
  textData: {
    marginRight: 10,
    fontSize: 15,
  },
  text2: {
    alignSelf: 'center',
  },
  pactHistori: {
    backgroundColor: '#FFFF',
    elevation: 5,
    height: 70,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '5%',
    marginBottom: 10,
  },
  iconOrder: {
    height: '70%',
    // width: '6%',
    marginRight: 10,
    maxWidth: 25,
  },
  text3: {
    fontSize: 10,
    color: '#a9a9',
    fontWeight: 'bold',
  },
  text4: {
    color: '#a0a0a0a0',
    fontWeight: 'bold',
  },
  text5: {
    color: '#4169e1',
    // textAlign: 'right',
  },
  see: {
    // borderWidth: 1,
    maxWidth: '25%',
    alignSelf: 'flex-end',
    marginHorizontal: 10,
    marginBottom: 8,
  },
  loading: {
    alignSelf: 'center',
  },
  loading2: {
    alignItems: 'center',
    alignSelf: 'center',
  },
  textAtention: {
    textAlign: 'center',
  },
  Loading1: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
});

export {styles};
